[project]
name = 'privacy-layer-for-bitcoin-transactions'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.privacy-layer]
path = 'contracts/privacy-layer.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
